title: Starfall Wiki
description: The Starfall Wiki

url: "https://star-pedestal-games.github.io/Starfall-Wiki"

markdown: GFM
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme

collections:
  de_de:
    permalink: /snippets/de_de/:path/

# show_downloads: false
# google_analytics: 12345
